using System.Collections.Immutable;

namespace ECBFinanceAPI.YieldCurves.Enums;

public enum ReferenceArea
{
    InternationalOrganisations,
    UNOrganisations,
    InternationalMonetaryFund,
    WorldTradeOrganisation,
    InternationalBankForReconstructionAndDevelopment,
    InternationalDevelopmentAssociation,
    OtherUNOrganisations,
    UNESCO,
    FAO,
    WHO,
    IFAD,
    IFC,
    MIGA,
    UNICEF,
    UNHCR,
    UNRWA,
    IAEA,
    ILO,
    ITU,
    WorldBank,
    RestOfUNOrganisations,
    EuropeanCommunityInstitutionsOrgansAndOrganisms,
    EMS,
    EuropeanInvestmentBank,
    EuropeanCommission,
    EuropeanDevelopmentFund,
    EuropeanCentralBank,
    EIF,
    EuropeanCommunityOfSteelAndCoal,
    NeighbourhoodInvestmentFacility,
    OtherECInstitutionsOrgansAndOrganisms,
    EuropeanParliament,
    CouncilOfTheEuropeanUnion,
    SRB,
    CourtOfAuditors,
    EuropeanCouncil,
    EconomicAndSocialCommittee,
    CommitteeOfRegions,
    EUAfricaInfrastructureTrustFund,
    EuropeanStabilityMechanism,
    JointCommitteeOfTheEuropeanSupervisoryAuthorities,
    FEMIP,
    EFSF,
    AllEUInstitutionsNotFinancedViaEUBudget,
    AllECInstitutionsIncludingECBESMEFSF,
    OtherECInstitutionsOrgansAndOrganisms2,
    OECD,
    BIS,
    InterAmericanDevelopmentBank,
    AfricanDevelopmentBank,
    AsianDevelopmentBank,
    EuropeanBankForReconstructionAndDevelopment,
    IIC,
    NIB,
    ECCB,
    IBEC,
    IIB,
    CDB,
    AMF,
    BADEA,
    BCEAO,
    CASDB,
    AfricanDevelopmentFund,
    AsianDevelopmentFund,
    FondsSpecialUnifieDeDeveloppement,
    CABEI,
    ADC,
    OtherInternationalOrganisationsFinancialInstitutions,
    BEAC,
    CEMAC,
    ECCU,
    OtherInternationalFinancialOrganisations,
    OtherInternationalOrganisationsNonFinancialInstitutions,
    NATO,
    CouncilOfEurope,
    ICRC,
    ESA,
    EPO,
    EUROCONTROL,
    EUTELSAT,
    EMBL,
    ITSO,
    EBUUER,
    EUMETSAT,
    ESO,
    ECMWF,
    OECD2,
    CERN,
    IOM,
    IslamicDevelopmentBank,
    EurasianDevelopmentBank,
    ParisClubCreditorInstitutions,
    CouncilOfEuropeDevelopmentBank,
    OtherInternationalNonFinancialOrganisations,
    WAEMU,
    InternationalOrganisationsExcludingEurCommunityInstitutions,
    InternationalUnionOfCreditAndInvestmentInsurers,
    OtherEEACountries,
    WorldAllEntities,
    EUR12,
    BelgoLuxembourgEconomicUnion,
    ExtraEUR12,
    EuropeanFreeTradeAssociation,
    EuropeanEconomicArea,
    ExtraEEA,
    Oecdcountries,
    CountriesFromCentralAndEasternEurope,
    Andorra,
    UnitedArabEmirates,
    Afghanistan,
    AntiguaAndBarbuda,
    Anguilla,
    Albania,
    Armenia,
    NetherlandsAntilles,
    Angola,
    Antarctica,
    Argentina,
    AmericanSamoa,
    Austria,
    Australia,
    Aruba,
    AlandIslands,
    Azerbaijan,
    EmergingAndDevelopingEconomies,
    NorthAmericanFreeTradeAssociation,
    LatinAmerica,
    CountriesForTheAssociationOfSouthEastAsianNations,
    OrganizationOfPetroleumExportingCountries,
    AfricanCaribbeanAndPacificCountries,
    AfricanACPCountries,
    CaribbeanACPCountries,
    PacificACPCountries,
    CoreNewlyIndustrializingCountries,
    BosniaAndHerzegovina,
    Barbados,
    Bangladesh,
    Belgium,
    BurkinaFaso,
    Bulgaria,
    Bahrain,
    Burundi,
    Benin,
    SaintBarthelemy,
    Bermuda,
    BruneiDarussalam,
    Bolivia,
    BonaireSaintEustatiusAndSaba,
    Brazil,
    Bahamas,
    Bhutan,
    BouvetIsland,
    Botswana,
    Belarus,
    Belize,
    AsianNICsSecondWave,
    LatinAmericanNICsSecondWave,
    MediterraneanBasinCountries,
    OffshoreFinancialCenters,
    FrenchFrancZone,
    CommunityOfIndependantStates,
    MaghrebCountries,
    MashrekCountries,
    Mercosur,
    Canada,
    CocosKeelingIslands,
    CongoDemocraticRepublic,
    CentralAfricanRepublic,
    Congo,
    Switzerland,
    CoteDIvoire,
    CookIslands,
    Chile,
    Cameroon,
    China,
    Colombia,
    CostaRica,
    SerbiaAndMontenegro,
    Cuba,
    CapeVerde,
    Curacao,
    ChristmasIsland,
    Cyprus,
    CzechRepublic,
    EUChangingComposition,
    AsiaPacificEconomicCooperation,
    EU15FixedComposition1995,
    EU25FixedComposition2004,
    ExtraEU15FixedComposition1995,
    ExtraEU25FixedComposition2004,
    CandidateCountries,
    MediterraneanCountriesEuroMediterraneanPartnership,
    NewEUMemberStates2004,
    ExtraEUChangingComposition,
    Germany,
    Djibouti,
    Denmark,
    Dominica,
    DominicanRepublic,
    Algeria,
    OtherNorthAmericanCountries,
    Europe,
    OtherEuropeanCountriesNotEUNorEFTA,
    BalticCountries,
    Africa,
    NorthAfricaCountries,
    CentralAndSouthAfricaCountries,
    America,
    NorthAmericanCountries,
    CentralAmericanCountries,
    Ecuador,
    Estonia,
    Egypt,
    WesternSahara,
    Eritrea,
    Spain,
    Ethiopia,
    AfricaAndMiddleEastCountries,
    SouthAmericanCountries,
    Asia,
    NearAndMiddleEastCountries,
    GulfArabianCountries,
    OtherNearAndMiddleEastCountries,
    OtherAsianCountries,
    AustraliaOceaniaAndOtherTerritories,
    AustralianOceania,
    AmericanOceania,
    Finland,
    Fiji,
    FalklandIslands,
    Micronesia,
    FaroeIslands,
    France,
    OtherEuropeanCountries,
    NewZealandOceania,
    PolarRegions,
    G20,
    Gabon,
    UnitedKingdom,
    Grenada,
    Georgia,
    FrenchGuiana,
    Guernsey,
    Ghana,
    Gibraltar,
    Greenland,
    Gambia,
    Guinea,
    Guadeloupe,
    EquatorialGuinea,
    Greece,
    SouthGeorgiaAndSouthSandwichIslands,
    Guatemala,
    Guam,
    GuineaBissau,
    Guyana,
    EEAExceptEuroAreaAndReferenceArea,
    HongKong,
    HeardIslandAndMcDonaldIslands,
    Honduras,
    Croatia,
    Haiti,
    Hungary,
    EuroArea11FixedComposition1999,
    EuroArea12FixedComposition2001,
    EuroArea13FixedComposition2007,
    EuroArea15FixedComposition2008,
    EuroArea16FixedComposition2009,
    EuroArea17FixedComposition2011,
    EuroArea18FixedComposition2014,
    EuroArea19FixedComposition2015,
    EuroArea20FixedComposition2023,
    EuroArea20FixedCompositionNotAllocated2023,
    Indonesia,
    Ireland,
    Israel,
    IsleOfMan,
    India,
    BritishIndianOceanTerritory,
    Iraq,
    Iran,
    Iceland,
    Italy,
    ExtraEuroArea11FixedComposition1999,
    ExtraEuroArea12FixedComposition2001,
    ExtraEuroArea13FixedComposition2007,
    ExtraEuroArea15FixedComposition2008,
    ExtraEuroArea16FixedComposition2009,
    ExtraEuroArea17FixedComposition2011,
    ExtraEuroArea18FixedComposition2014,
    ExtraEuroArea19FixedComposition2015,
    ExtraEuroArea20FixedComposition2023,
    ExtraEuroArea20FixedCompositionNotAllocated2023,
    Jersey,
    Jamaica,
    Jordan,
    Japan,
    EU27NotEuroArea19FixedComposition2020,
    EUMemberStatesNotEuroArea11FixedComposition1999,
    EU27NotEuroArea20FixedComposition2023,
    EU27NotEuroArea20FixedCompositionEUInstitutions2023,
    EUMemberStatesNotEuroArea12FixedComposition2001,
    EUMemberStatesNotEuroArea13FixedComposition2007,
    EUMemberStatesNotEuroArea15FixedComposition2008,
    EUMemberStatesNotEuroArea16FixedComposition2009,
    EUMemberStatesNotEuroArea17FixedComposition2011,
    EU28NotEuroArea17FixedComposition2013,
    EU28NotEuroArea18FixedComposition2014,
    EU28NotEuroArea19FixedComposition2015,
    Kenya,
    Kyrgyzstan,
    Cambodia,
    Kiribati,
    Comoros,
    SaintKittsAndNevis,
    KoreaDemocraticPeoplesRepublic,
    KoreaRepublicOf,
    Kuwait,
    CaymanIslands,
    Kazakhstan,
    OtherEUMemberStates,
    OtherEuroArea11MemberStates1999,
    OtherEuroArea12MemberStates2001,
    OtherEuroArea13MemberStates2007,
    OtherEuroArea15MemberStates2008,
    OtherEuroArea16MemberStates2009,
    OtherEuroArea17MemberStates2011,
    OtherEuroArea18MemberStates2014,
    OtherEuroArea19MemberStates2015,
    LaoPeoplesDemocraticRepublic,
    Lebanon,
    SaintLucia,
    Liechtenstein,
    SriLanka,
    Liberia,
    Lesotho,
    Lithuania,
    Luxembourg,
    Latvia,
    Libya,
    AllAreasOtherThanEU15AndReferenceArea1995,
    AllAreasOtherThanEuroArea11AndReferenceArea1999,
    AllAreasOtherThanEuroArea12AndReferenceArea2001,
    AllAreasOtherThanEuroArea13AndReferenceArea2007,
    AllAreasOtherThanEuroArea15AndReferenceArea2008,
    AllAreasOtherThanEuroArea16AndReferenceArea2009,
    AllAreasOtherThanEuroArea17AndReferenceArea2011,
    AllAreasOtherThanEuroArea18AndReferenceArea2014,
    AllAreasOtherThanEuroArea19AndReferenceArea2015,
    Morocco,
    Monaco,
    Moldova,
    Montenegro,
    SaintMartinFrenchPart,
    Madagascar,
    MarshallIslands,
    RepublicOfNorthMacedonia,
    Mali,
    Myanmar,
    Mongolia,
    Macao,
    NorthernMarianaIslands,
    Martinique,
    Mauritania,
    Montserrat,
    Malta,
    Mauritius,
    Maldives,
    Malawi,
    Mexico,
    Malaysia,
    Mozambique,
    IntraEUExtraEuroAreaNotAllocated,
    IntraEuroArea11NotAllocated1999,
    IntraEuroArea12NotAllocated2001,
    IntraEuroArea13NotAllocated2007,
    IntraEuroArea15NotAllocated2008,
    IntraEuroArea16NotAllocated2009,
    IntraEuroArea17NotAllocated2011,
    Namibia,
    NewCaledonia,
    Niger,
    NorfolkIsland,
    Nigeria,
    Nicaragua,
    Netherlands,
    Norway,
    Nepal,
    Nauru,
    Niue,
    NewZealand,
    ExtraEuroArea11NotAllocated1999,
    ExtraEuroArea12NotAllocated2001,
    ExtraEuroArea13NotAllocated2007,
    ExtraEuroArea15NotAllocated2008,
    ExtraEuroArea16NotAllocated2009,
    ExtraEuroArea17NotAllocated2011,
    Oman,
    WorldNotAllocatedEuroArea11,
    WorldNotAllocatedEuroArea12,
    WorldNotAllocatedEuroArea13,
    WorldNotAllocatedEuroArea15,
    WorldNotAllocatedEuroArea16,
    WorldNotAllocatedEuroArea17,
    Panama,
    Peru,
    FrenchPolynesia,
    PapuaNewGuinea,
    Philippines,
    Pakistan,
    Poland,
    SaintPierreAndMiquelon,
    Pitcairn,
    PuertoRico,
    PalestinianTerritoryOccupied,
    Portugal,
    Palau,
    Paraguay,
    EU28OutsideEuroArea18ExcludingDKSEGB2014,
    EU28OutsideEuroArea19ExcludingDKSEGB2015,
    EU27OutsideEuroArea20ExcludingDKSE2023,
    Qatar,
    CandidateCountriesISMEMKRS,
    WestGermany,
    EastGermany,
    CandidatesCountriesHRMKTR,
    CandidateCountriesHRISMKTR,
    NewEUMemberStatesJoining20042007,
    CandidateCountriesHRISMEMKTR,
    Reunion,
    Romania,
    Serbia,
    RussianFederation,
    Rwanda,
    EuroAreaMovingConcept,
    EU15FixedCompositionExcludingLU1995,
    EU12FixedCompositionIncludingWestGermany1993,
    EU27OutsideEuroArea13ExcludingDKSEGB2007,
    EU27OutsideEuroArea15ExcludingDKSEGB2008,
    EU27OutsideEuroArea16ExcludingDKSEGB2009,
    EU27OutsideEuroArea17ExcludingDKSEGB2011,
    EU28OutsideEuroArea17ExcludingDKSEGB2013,
    SaudiArabia,
    SolomonIslands,
    Seychelles,
    Sudan,
    Sweden,
    Singapore,
    SaintHelena,
    Slovenia,
    SvalbardAndJanMayen,
    Slovakia,
    SierraLeone,
    SanMarino,
    Senegal,
    Somalia,
    Suriname,
    SouthSudan,
    SaoTomeAndPrincipe,
    ElSalvador,
    SintMaartenDutchPart,
    SyrianArabRepublic,
    Swaziland,
    EuroArea11ExcludingLU1999,
    EuroAreaCountriesExceptGermanyFranceItalySpain,
    EuroAreaCountriesMovingExcludingDEFR,
    TurksAndCaicosIslands,
    Chad,
    FrenchSouthernTerritories,
    Togo,
    Thailand,
    Tajikistan,
    Tokelau,
    TimorLeste,
    Turkmenistan,
    Tunisia,
    Tonga,
    Turkey,
    TrinidadAndTobago,
    Tuvalu,
    Taiwan,
    Tanzania,
    EUExcludingEuroAreaAndReferenceArea,
    EuroAreaChangingComposition,
    EUMemberStatesNotBelongingToEuroArea,
    ExtraEuroArea,
    OtherEuroAreaMemberStates,
    Domestic,
    EuroAreaAndReferenceArea,
    AllAreasOtherThanEuroAreaAndReferenceArea,
    AllAreasOtherThanEUAndReferenceArea,
    Ukraine,
    Uganda,
    UnitedStatesMinorOutlyingIslands,
    UnitedStates,
    Uruguay,
    Uzbekistan,
    EU27FixedComposition2007,
    ExtraEU27FixedComposition2007,
    EU28FixedComposition2013,
    ExtraEU28FixedComposition2013,
    EU27FixedComposition2020,
    ExtraEU27FixedComposition2020,
    HolySee,
    SaintVincentAndTheGrenadines,
    Venezuela,
    VirginIslandsBritish,
    VirginIslandsUS,
    VietNam,
    Vanuatu,
    IntraEUChangingCompositionNotAllocated,
    GazaAndJericho,
    IntraEuroAreaNotAllocated,
    ExtraEuroAreaNotAllocated,
    ExtraEU25NotAllocated2004,
    ResidualForBOPAndIIPStep3ECBNeeds,
    IntraEU25NotAllocated2004,
    IntraEU27NotAllocated2007,
    ExtraEU27NotAllocated2007,
    WallisAndFutuna,
    Samoa,
    NotApplicable,
    Kosovo,
    Yemen,
    Mayotte,
    Yugoslavia,
    WorldNotAllocatedEU12,
    WorldNotAllocatedEU15,
    SmallEuroAreaCountries,
    IntraEU12NotAllocated1993,
    WorldNotAllocatedEuroArea,
    ExtraEU12NotAllocated1993,
    WorldNotAllocatedGeographically,
    IntraEU15NotAllocated1995,
    EquallySharedControlOfUCIs,
    ExtraEU15NotAllocated1995,
    RestOfTheWorld,
    SouthAfrica,
    Zambia,
    Zimbabwe
}

internal static class ReferenceAreaMappings
{
    public static readonly ImmutableDictionary<ReferenceArea, string> ReferenceAreaToCode = new Dictionary<ReferenceArea, string>()
    {
        {ReferenceArea.InternationalOrganisations, "1A"},
        {ReferenceArea.UNOrganisations, "1B"},
        {ReferenceArea.InternationalMonetaryFund, "1C"},
        {ReferenceArea.WorldTradeOrganisation, "1D"},
        {ReferenceArea.InternationalBankForReconstructionAndDevelopment, "1E"},
        {ReferenceArea.InternationalDevelopmentAssociation, "1F"},
        {ReferenceArea.OtherUNOrganisations, "1G"},
        {ReferenceArea.UNESCO, "1H"},
        {ReferenceArea.FAO, "1J"},
        {ReferenceArea.WHO, "1K"},
        {ReferenceArea.IFAD, "1L"},
        {ReferenceArea.IFC, "1M"},
        {ReferenceArea.MIGA, "1N"},
        {ReferenceArea.UNICEF, "1O"},
        {ReferenceArea.UNHCR, "1P"},
        {ReferenceArea.UNRWA, "1Q"},
        {ReferenceArea.IAEA, "1R"},
        {ReferenceArea.ILO, "1S"},
        {ReferenceArea.ITU, "1T"},
        {ReferenceArea.WorldBank, "1W"},
        {ReferenceArea.RestOfUNOrganisations, "1Z"},
        {ReferenceArea.EuropeanCommunityInstitutionsOrgansAndOrganisms, "4A"},
        {ReferenceArea.EMS, "4B"},
        {ReferenceArea.EuropeanInvestmentBank, "4C"},
        {ReferenceArea.EuropeanCommission, "4D"},
        {ReferenceArea.EuropeanDevelopmentFund, "4E"},
        {ReferenceArea.EuropeanCentralBank, "4F"},
        {ReferenceArea.EIF, "4G"},
        {ReferenceArea.EuropeanCommunityOfSteelAndCoal, "4H"},
        {ReferenceArea.NeighbourhoodInvestmentFacility, "4I"},
        {ReferenceArea.OtherECInstitutionsOrgansAndOrganisms, "4J"},
        {ReferenceArea.EuropeanParliament, "4K"},
        {ReferenceArea.CouncilOfTheEuropeanUnion, "4L"},
        {ReferenceArea.SRB, "4M"},
        {ReferenceArea.CourtOfAuditors, "4N"},
        {ReferenceArea.EuropeanCouncil, "4O"},
        {ReferenceArea.EconomicAndSocialCommittee, "4P"},
        {ReferenceArea.CommitteeOfRegions, "4Q"},
        {ReferenceArea.EUAfricaInfrastructureTrustFund, "4R"},
        {ReferenceArea.EuropeanStabilityMechanism, "4S"},
        {ReferenceArea.JointCommitteeOfTheEuropeanSupervisoryAuthorities, "4T"},
        {ReferenceArea.FEMIP, "4V"},
        {ReferenceArea.EFSF, "4W"},
        {ReferenceArea.AllEUInstitutionsNotFinancedViaEUBudget, "4X"},
        {ReferenceArea.AllECInstitutionsIncludingECBESMEFSF, "4Y"},
        {ReferenceArea.OtherECInstitutionsOrgansAndOrganisms2, "4Z"},
        {ReferenceArea.OECD, "5A"},
        {ReferenceArea.BIS, "5B"},
        {ReferenceArea.InterAmericanDevelopmentBank, "5C"},
        {ReferenceArea.AfricanDevelopmentBank, "5D"},
        {ReferenceArea.AsianDevelopmentBank, "5E"},
        {ReferenceArea.EuropeanBankForReconstructionAndDevelopment, "5F"},
        {ReferenceArea.IIC, "5G"},
        {ReferenceArea.NIB, "5H"},
        {ReferenceArea.ECCB, "5I"},
        {ReferenceArea.IBEC, "5J"},
        {ReferenceArea.IIB, "5K"},
        {ReferenceArea.CDB, "5L"},
        {ReferenceArea.AMF, "5M"},
        {ReferenceArea.BADEA, "5N"},
        {ReferenceArea.BCEAO, "5O"},
        {ReferenceArea.CASDB, "5P"},
        {ReferenceArea.AfricanDevelopmentFund, "5Q"},
        {ReferenceArea.AsianDevelopmentFund, "5R"},
        {ReferenceArea.FondsSpecialUnifieDeDeveloppement, "5S"},
        {ReferenceArea.CABEI, "5T"},
        {ReferenceArea.ADC, "5U"},
        {ReferenceArea.OtherInternationalOrganisationsFinancialInstitutions, "5V"},
        {ReferenceArea.BEAC, "5W"},
        {ReferenceArea.CEMAC, "5X"},
        {ReferenceArea.ECCU, "5Y"},
        {ReferenceArea.OtherInternationalFinancialOrganisations, "5Z"},
        {ReferenceArea.OtherInternationalOrganisationsNonFinancialInstitutions, "6A"},
        {ReferenceArea.NATO, "6B"},
        {ReferenceArea.CouncilOfEurope, "6C"},
        {ReferenceArea.ICRC, "6D"},
        {ReferenceArea.ESA, "6E"},
        {ReferenceArea.EPO, "6F"},
        {ReferenceArea.EUROCONTROL, "6G"},
        {ReferenceArea.EUTELSAT, "6H"},
        {ReferenceArea.EMBL, "6I"},
        {ReferenceArea.ITSO, "6J"},
        {ReferenceArea.EBUUER, "6K"},
        {ReferenceArea.EUMETSAT, "6L"},
        {ReferenceArea.ESO, "6M"},
        {ReferenceArea.ECMWF, "6N"},
        {ReferenceArea.OECD2, "6O"},
        {ReferenceArea.CERN, "6P"},
        {ReferenceArea.IOM, "6Q"},
        {ReferenceArea.IslamicDevelopmentBank, "6R"},
        {ReferenceArea.EurasianDevelopmentBank, "6S"},
        {ReferenceArea.ParisClubCreditorInstitutions, "6T"},
        {ReferenceArea.CouncilOfEuropeDevelopmentBank, "6U"},
        {ReferenceArea.OtherInternationalNonFinancialOrganisations, "6Z"},
        {ReferenceArea.WAEMU, "7A"},
        {ReferenceArea.InternationalOrganisationsExcludingEurCommunityInstitutions, "7Z"},
        {ReferenceArea.InternationalUnionOfCreditAndInvestmentInsurers, "8A"},
        {ReferenceArea.OtherEEACountries, "A0"},
        {ReferenceArea.WorldAllEntities, "A1"},
        {ReferenceArea.EUR12, "A2"},
        {ReferenceArea.BelgoLuxembourgEconomicUnion, "A3"},
        {ReferenceArea.ExtraEUR12, "A4"},
        {ReferenceArea.EuropeanFreeTradeAssociation, "A5"},
        {ReferenceArea.EuropeanEconomicArea, "A6"},
        {ReferenceArea.ExtraEEA, "A7"},
        {ReferenceArea.Oecdcountries, "A8"},
        {ReferenceArea.CountriesFromCentralAndEasternEurope, "A9"},
        {ReferenceArea.Andorra, "AD"},
        {ReferenceArea.UnitedArabEmirates, "AE"},
        {ReferenceArea.Afghanistan, "AF"},
        {ReferenceArea.AntiguaAndBarbuda, "AG"},
        {ReferenceArea.Anguilla, "AI"},
        {ReferenceArea.Albania, "AL"},
        {ReferenceArea.Armenia, "AM"},
        {ReferenceArea.NetherlandsAntilles, "AN"},
        {ReferenceArea.Angola, "AO"},
        {ReferenceArea.Antarctica, "AQ"},
        {ReferenceArea.Argentina, "AR"},
        {ReferenceArea.AmericanSamoa, "AS"},
        {ReferenceArea.Austria, "AT"},
        {ReferenceArea.Australia, "AU"},
        {ReferenceArea.Aruba, "AW"},
        {ReferenceArea.AlandIslands, "AX"},
        {ReferenceArea.Azerbaijan, "AZ"},
        {ReferenceArea.EmergingAndDevelopingEconomies, "B0"},
        {ReferenceArea.NorthAmericanFreeTradeAssociation, "B1"},
        {ReferenceArea.LatinAmerica, "B2"},
        {ReferenceArea.CountriesForTheAssociationOfSouthEastAsianNations, "B3"},
        {ReferenceArea.OrganizationOfPetroleumExportingCountries, "B4"},
        {ReferenceArea.AfricanCaribbeanAndPacificCountries, "B5"},
        {ReferenceArea.AfricanACPCountries, "B6"},
        {ReferenceArea.CaribbeanACPCountries, "B7"},
        {ReferenceArea.PacificACPCountries, "B8"},
        {ReferenceArea.CoreNewlyIndustrializingCountries, "B9"},
        {ReferenceArea.BosniaAndHerzegovina, "BA"},
        {ReferenceArea.Barbados, "BB"},
        {ReferenceArea.Bangladesh, "BD"},
        {ReferenceArea.Belgium, "BE"},
        {ReferenceArea.BurkinaFaso, "BF"},
        {ReferenceArea.Bulgaria, "BG"},
        {ReferenceArea.Bahrain, "BH"},
        {ReferenceArea.Burundi, "BI"},
        {ReferenceArea.Benin, "BJ"},
        {ReferenceArea.SaintBarthelemy, "BL"},
        {ReferenceArea.Bermuda, "BM"},
        {ReferenceArea.BruneiDarussalam, "BN"},
        {ReferenceArea.Bolivia, "BO"},
        {ReferenceArea.BonaireSaintEustatiusAndSaba, "BQ"},
        {ReferenceArea.Brazil, "BR"},
        {ReferenceArea.Bahamas, "BS"},
        {ReferenceArea.Bhutan, "BT"},
        {ReferenceArea.BouvetIsland, "BV"},
        {ReferenceArea.Botswana, "BW"},
        {ReferenceArea.Belarus, "BY"},
        {ReferenceArea.Belize, "BZ"},
        {ReferenceArea.AsianNICsSecondWave, "C1"},
        {ReferenceArea.LatinAmericanNICsSecondWave, "C2"},
        {ReferenceArea.MediterraneanBasinCountries, "C3"},
        {ReferenceArea.OffshoreFinancialCenters, "C4"},
        {ReferenceArea.FrenchFrancZone, "C5"},
        {ReferenceArea.CommunityOfIndependantStates, "C6"},
        {ReferenceArea.MaghrebCountries, "C7"},
        {ReferenceArea.MashrekCountries, "C8"},
        {ReferenceArea.Mercosur, "C9"},
        {ReferenceArea.Canada, "CA"},
        {ReferenceArea.CocosKeelingIslands, "CC"},
        {ReferenceArea.CongoDemocraticRepublic, "CD"},
        {ReferenceArea.CentralAfricanRepublic, "CF"},
        {ReferenceArea.Congo, "CG"},
        {ReferenceArea.Switzerland, "CH"},
        {ReferenceArea.CoteDIvoire, "CI"},
        {ReferenceArea.CookIslands, "CK"},
        {ReferenceArea.Chile, "CL"},
        {ReferenceArea.Cameroon, "CM"},
        {ReferenceArea.China, "CN"},
        {ReferenceArea.Colombia, "CO"},
        {ReferenceArea.CostaRica, "CR"},
        {ReferenceArea.SerbiaAndMontenegro, "CS"},
        {ReferenceArea.Cuba, "CU"},
        {ReferenceArea.CapeVerde, "CV"},
        {ReferenceArea.Curacao, "CW"},
        {ReferenceArea.ChristmasIsland, "CX"},
        {ReferenceArea.Cyprus, "CY"},
        {ReferenceArea.CzechRepublic, "CZ"},
        {ReferenceArea.EUChangingComposition, "D0"},
        {ReferenceArea.AsiaPacificEconomicCooperation, "D1"},
        {ReferenceArea.EU15FixedComposition1995, "D2"},
        {ReferenceArea.EU25FixedComposition2004, "D3"},
        {ReferenceArea.ExtraEU15FixedComposition1995, "D4"},
        {ReferenceArea.ExtraEU25FixedComposition2004, "D5"},
        {ReferenceArea.CandidateCountries, "D6"},
        {ReferenceArea.MediterraneanCountriesEuroMediterraneanPartnership, "D7"},
        {ReferenceArea.NewEUMemberStates2004, "D8"},
        {ReferenceArea.ExtraEUChangingComposition, "D9"},
        {ReferenceArea.Germany, "DE"},
        {ReferenceArea.Djibouti, "DJ"},
        {ReferenceArea.Denmark, "DK"},
        {ReferenceArea.Dominica, "DM"},
        {ReferenceArea.DominicanRepublic, "DO"},
        {ReferenceArea.Algeria, "DZ"},
        {ReferenceArea.OtherNorthAmericanCountries, "E0"},
        {ReferenceArea.Europe, "E1"},
        {ReferenceArea.OtherEuropeanCountriesNotEUNorEFTA, "E2"},
        {ReferenceArea.BalticCountries, "E3"},
        {ReferenceArea.Africa, "E4"},
        {ReferenceArea.NorthAfricaCountries, "E5"},
        {ReferenceArea.CentralAndSouthAfricaCountries, "E6"},
        {ReferenceArea.America, "E7"},
        {ReferenceArea.NorthAmericanCountries, "E8"},
        {ReferenceArea.CentralAmericanCountries, "E9"},
        {ReferenceArea.Ecuador, "EC"},
        {ReferenceArea.Estonia, "EE"},
        {ReferenceArea.Egypt, "EG"},
        {ReferenceArea.WesternSahara, "EH"},
        {ReferenceArea.Eritrea, "ER"},
        {ReferenceArea.Spain, "ES"},
        {ReferenceArea.Ethiopia, "ET"},
        {ReferenceArea.AfricaAndMiddleEastCountries, "F0"},
        {ReferenceArea.SouthAmericanCountries, "F1"},
        {ReferenceArea.Asia, "F2"},
        {ReferenceArea.NearAndMiddleEastCountries, "F3"},
        {ReferenceArea.GulfArabianCountries, "F4"},
        {ReferenceArea.OtherNearAndMiddleEastCountries, "F5"},
        {ReferenceArea.OtherAsianCountries, "F6"},
        {ReferenceArea.AustraliaOceaniaAndOtherTerritories, "F7"},
        {ReferenceArea.AustralianOceania, "F8"},
        {ReferenceArea.AmericanOceania, "F9"},
        {ReferenceArea.Finland, "FI"},
        {ReferenceArea.Fiji, "FJ"},
        {ReferenceArea.FalklandIslands, "FK"},
        {ReferenceArea.Micronesia, "FM"},
        {ReferenceArea.FaroeIslands, "FO"},
        {ReferenceArea.France, "FR"},
        {ReferenceArea.OtherEuropeanCountries, "G0"},
        {ReferenceArea.NewZealandOceania, "G1"},
        {ReferenceArea.PolarRegions, "G2"},
        {ReferenceArea.G20, "G3"},
        {ReferenceArea.Gabon, "GA"},
        {ReferenceArea.UnitedKingdom, "GB"},
        {ReferenceArea.Grenada, "GD"},
        {ReferenceArea.Georgia, "GE"},
        {ReferenceArea.FrenchGuiana, "GF"},
        {ReferenceArea.Guernsey, "GG"},
        {ReferenceArea.Ghana, "GH"},
        {ReferenceArea.Gibraltar, "GI"},
        {ReferenceArea.Greenland, "GL"},
        {ReferenceArea.Gambia, "GM"},
        {ReferenceArea.Guinea, "GN"},
        {ReferenceArea.Guadeloupe, "GP"},
        {ReferenceArea.EquatorialGuinea, "GQ"},
        {ReferenceArea.Greece, "GR"},
        {ReferenceArea.SouthGeorgiaAndSouthSandwichIslands, "GS"},
        {ReferenceArea.Guatemala, "GT"},
        {ReferenceArea.Guam, "GU"},
        {ReferenceArea.GuineaBissau, "GW"},
        {ReferenceArea.Guyana, "GY"},
        {ReferenceArea.EEAExceptEuroAreaAndReferenceArea, "H0"},
        {ReferenceArea.HongKong, "HK"},
        {ReferenceArea.HeardIslandAndMcDonaldIslands, "HM"},
        {ReferenceArea.Honduras, "HN"},
        {ReferenceArea.Croatia, "HR"},
        {ReferenceArea.Haiti, "HT"},
        {ReferenceArea.Hungary, "HU"},
        {ReferenceArea.EuroArea11FixedComposition1999, "I1"},
        {ReferenceArea.EuroArea12FixedComposition2001, "I2"},
        {ReferenceArea.EuroArea13FixedComposition2007, "I3"},
        {ReferenceArea.EuroArea15FixedComposition2008, "I4"},
        {ReferenceArea.EuroArea16FixedComposition2009, "I5"},
        {ReferenceArea.EuroArea17FixedComposition2011, "I6"},
        {ReferenceArea.EuroArea18FixedComposition2014, "I7"},
        {ReferenceArea.EuroArea19FixedComposition2015, "I8"},
        {ReferenceArea.EuroArea20FixedComposition2023, "I9"},
        {ReferenceArea.EuroArea20FixedCompositionNotAllocated2023, "I99"},
        {ReferenceArea.Indonesia, "ID"},
        {ReferenceArea.Ireland, "IE"},
        {ReferenceArea.Israel, "IL"},
        {ReferenceArea.IsleOfMan, "IM"},
        {ReferenceArea.India, "IN"},
        {ReferenceArea.BritishIndianOceanTerritory, "IO"},
        {ReferenceArea.Iraq, "IQ"},
        {ReferenceArea.Iran, "IR"},
        {ReferenceArea.Iceland, "IS"},
        {ReferenceArea.Italy, "IT"},
        {ReferenceArea.ExtraEuroArea11FixedComposition1999, "J1"},
        {ReferenceArea.ExtraEuroArea12FixedComposition2001, "J2"},
        {ReferenceArea.ExtraEuroArea13FixedComposition2007, "J3"},
        {ReferenceArea.ExtraEuroArea15FixedComposition2008, "J4"},
        {ReferenceArea.ExtraEuroArea16FixedComposition2009, "J5"},
        {ReferenceArea.ExtraEuroArea17FixedComposition2011, "J6"},
        {ReferenceArea.ExtraEuroArea18FixedComposition2014, "J7"},
        {ReferenceArea.ExtraEuroArea19FixedComposition2015, "J8"},
        {ReferenceArea.ExtraEuroArea20FixedComposition2023, "J9"},
        {ReferenceArea.ExtraEuroArea20FixedCompositionNotAllocated2023, "J99"},
        {ReferenceArea.Jersey, "JE"},
        {ReferenceArea.Jamaica, "JM"},
        {ReferenceArea.Jordan, "JO"},
        {ReferenceArea.Japan, "JP"},
        {ReferenceArea.EU27NotEuroArea19FixedComposition2020, "K0"},
        {ReferenceArea.EUMemberStatesNotEuroArea11FixedComposition1999, "K1"},
        {ReferenceArea.EU27NotEuroArea20FixedComposition2023, "K11"},
        {ReferenceArea.EU27NotEuroArea20FixedCompositionEUInstitutions2023, "K11A"},
        {ReferenceArea.EUMemberStatesNotEuroArea12FixedComposition2001, "K2"},
        {ReferenceArea.EUMemberStatesNotEuroArea13FixedComposition2007, "K3"},
        {ReferenceArea.EUMemberStatesNotEuroArea15FixedComposition2008, "K4"},
        {ReferenceArea.EUMemberStatesNotEuroArea16FixedComposition2009, "K5"},
        {ReferenceArea.EUMemberStatesNotEuroArea17FixedComposition2011, "K6"},
        {ReferenceArea.EU28NotEuroArea17FixedComposition2013, "K7"},
        {ReferenceArea.EU28NotEuroArea18FixedComposition2014, "K8"},
        {ReferenceArea.EU28NotEuroArea19FixedComposition2015, "K9"},
        {ReferenceArea.Kenya, "KE"},
        {ReferenceArea.Kyrgyzstan, "KG"},
        {ReferenceArea.Cambodia, "KH"},
        {ReferenceArea.Kiribati, "KI"},
        {ReferenceArea.Comoros, "KM"},
        {ReferenceArea.SaintKittsAndNevis, "KN"},
        {ReferenceArea.KoreaDemocraticPeoplesRepublic, "KP"},
        {ReferenceArea.KoreaRepublicOf, "KR"},
        {ReferenceArea.Kuwait, "KW"},
        {ReferenceArea.CaymanIslands, "KY"},
        {ReferenceArea.Kazakhstan, "KZ"},
        {ReferenceArea.OtherEUMemberStates, "L0"},
        {ReferenceArea.OtherEuroArea11MemberStates1999, "L1"},
        {ReferenceArea.OtherEuroArea12MemberStates2001, "L2"},
        {ReferenceArea.OtherEuroArea13MemberStates2007, "L3"},
        {ReferenceArea.OtherEuroArea15MemberStates2008, "L4"},
        {ReferenceArea.OtherEuroArea16MemberStates2009, "L5"},
        {ReferenceArea.OtherEuroArea17MemberStates2011, "L6"},
        {ReferenceArea.OtherEuroArea18MemberStates2014, "L7"},
        {ReferenceArea.OtherEuroArea19MemberStates2015, "L8"},
        {ReferenceArea.LaoPeoplesDemocraticRepublic, "LA"},
        {ReferenceArea.Lebanon, "LB"},
        {ReferenceArea.SaintLucia, "LC"},
        {ReferenceArea.Liechtenstein, "LI"},
        {ReferenceArea.SriLanka, "LK"},
        {ReferenceArea.Liberia, "LR"},
        {ReferenceArea.Lesotho, "LS"},
        {ReferenceArea.Lithuania, "LT"},
        {ReferenceArea.Luxembourg, "LU"},
        {ReferenceArea.Latvia, "LV"},
        {ReferenceArea.Libya, "LY"},
        {ReferenceArea.AllAreasOtherThanEU15AndReferenceArea1995, "M0"},
        {ReferenceArea.AllAreasOtherThanEuroArea11AndReferenceArea1999, "M1"},
        {ReferenceArea.AllAreasOtherThanEuroArea12AndReferenceArea2001, "M2"},
        {ReferenceArea.AllAreasOtherThanEuroArea13AndReferenceArea2007, "M3"},
        {ReferenceArea.AllAreasOtherThanEuroArea15AndReferenceArea2008, "M4"},
        {ReferenceArea.AllAreasOtherThanEuroArea16AndReferenceArea2009, "M5"},
        {ReferenceArea.AllAreasOtherThanEuroArea17AndReferenceArea2011, "M6"},
        {ReferenceArea.AllAreasOtherThanEuroArea18AndReferenceArea2014, "M7"},
        {ReferenceArea.AllAreasOtherThanEuroArea19AndReferenceArea2015, "M8"},
        {ReferenceArea.Morocco, "MA"},
        {ReferenceArea.Monaco, "MC"},
        {ReferenceArea.Moldova, "MD"},
        {ReferenceArea.Montenegro, "ME"},
        {ReferenceArea.SaintMartinFrenchPart, "MF"},
        {ReferenceArea.Madagascar, "MG"},
        {ReferenceArea.MarshallIslands, "MH"},
        {ReferenceArea.RepublicOfNorthMacedonia, "MK"},
        {ReferenceArea.Mali, "ML"},
        {ReferenceArea.Myanmar, "MM"},
        {ReferenceArea.Mongolia, "MN"},
        {ReferenceArea.Macao, "MO"},
        {ReferenceArea.NorthernMarianaIslands, "MP"},
        {ReferenceArea.Martinique, "MQ"},
        {ReferenceArea.Mauritania, "MR"},
        {ReferenceArea.Montserrat, "MS"},
        {ReferenceArea.Malta, "MT"},
        {ReferenceArea.Mauritius, "MU"},
        {ReferenceArea.Maldives, "MV"},
        {ReferenceArea.Malawi, "MW"},
        {ReferenceArea.Mexico, "MX"},
        {ReferenceArea.Malaysia, "MY"},
        {ReferenceArea.Mozambique, "MZ"},
        {ReferenceArea.IntraEUExtraEuroAreaNotAllocated, "N0"},
        {ReferenceArea.IntraEuroArea11NotAllocated1999, "N1"},
        {ReferenceArea.IntraEuroArea12NotAllocated2001, "N2"},
        {ReferenceArea.IntraEuroArea13NotAllocated2007, "N3"},
        {ReferenceArea.IntraEuroArea15NotAllocated2008, "N4"},
        {ReferenceArea.IntraEuroArea16NotAllocated2009, "N5"},
        {ReferenceArea.IntraEuroArea17NotAllocated2011, "N6"},
        {ReferenceArea.Namibia, "NA"},
        {ReferenceArea.NewCaledonia, "NC"},
        {ReferenceArea.Niger, "NE"},
        {ReferenceArea.NorfolkIsland, "NF"},
        {ReferenceArea.Nigeria, "NG"},
        {ReferenceArea.Nicaragua, "NI"},
        {ReferenceArea.Netherlands, "NL"},
        {ReferenceArea.Norway, "NO"},
        {ReferenceArea.Nepal, "NP"},
        {ReferenceArea.Nauru, "NR"},
        {ReferenceArea.Niue, "NU"},
        {ReferenceArea.NewZealand, "NZ"},
        {ReferenceArea.ExtraEuroArea11NotAllocated1999, "O1"},
        {ReferenceArea.ExtraEuroArea12NotAllocated2001, "O2"},
        {ReferenceArea.ExtraEuroArea13NotAllocated2007, "O3"},
        {ReferenceArea.ExtraEuroArea15NotAllocated2008, "O4"},
        {ReferenceArea.ExtraEuroArea16NotAllocated2009, "O5"},
        {ReferenceArea.ExtraEuroArea17NotAllocated2011, "O6"},
        {ReferenceArea.Oman, "OM"},
        {ReferenceArea.WorldNotAllocatedEuroArea11, "P1"},
        {ReferenceArea.WorldNotAllocatedEuroArea12, "P2"},
        {ReferenceArea.WorldNotAllocatedEuroArea13, "P3"},
        {ReferenceArea.WorldNotAllocatedEuroArea15, "P4"},
        {ReferenceArea.WorldNotAllocatedEuroArea16, "P5"},
        {ReferenceArea.WorldNotAllocatedEuroArea17, "P6"},
        {ReferenceArea.Panama, "PA"},
        {ReferenceArea.Peru, "PE"},
        {ReferenceArea.FrenchPolynesia, "PF"},
        {ReferenceArea.PapuaNewGuinea, "PG"},
        {ReferenceArea.Philippines, "PH"},
        {ReferenceArea.Pakistan, "PK"},
        {ReferenceArea.Poland, "PL"},
        {ReferenceArea.SaintPierreAndMiquelon, "PM"},
        {ReferenceArea.Pitcairn, "PN"},
        {ReferenceArea.PuertoRico, "PR"},
        {ReferenceArea.PalestinianTerritoryOccupied, "PS"},
        {ReferenceArea.Portugal, "PT"},
        {ReferenceArea.Palau, "PW"},
        {ReferenceArea.Paraguay, "PY"},
        {ReferenceArea.EU28OutsideEuroArea18ExcludingDKSEGB2014, "Q6"},
        {ReferenceArea.EU28OutsideEuroArea19ExcludingDKSEGB2015, "Q7"},
        {ReferenceArea.EU27OutsideEuroArea20ExcludingDKSE2023, "Q8"},
        {ReferenceArea.Qatar, "QA"},
        {ReferenceArea.CandidateCountriesISMEMKRS, "R0"},
        {ReferenceArea.WestGermany, "R1"},
        {ReferenceArea.EastGermany, "R2"},
        {ReferenceArea.CandidatesCountriesHRMKTR, "R6"},
        {ReferenceArea.CandidateCountriesHRISMKTR, "R7"},
        {ReferenceArea.NewEUMemberStatesJoining20042007, "R8"},
        {ReferenceArea.CandidateCountriesHRISMEMKTR, "R9"},
        {ReferenceArea.Reunion, "RE"},
        {ReferenceArea.Romania, "RO"},
        {ReferenceArea.Serbia, "RS"},
        {ReferenceArea.RussianFederation, "RU"},
        {ReferenceArea.Rwanda, "RW"},
        {ReferenceArea.EuroAreaMovingConcept, "S0"},
        {ReferenceArea.EU15FixedCompositionExcludingLU1995, "S1"},
        {ReferenceArea.EU12FixedCompositionIncludingWestGermany1993, "S2"},
        {ReferenceArea.EU27OutsideEuroArea13ExcludingDKSEGB2007, "S3"},
        {ReferenceArea.EU27OutsideEuroArea15ExcludingDKSEGB2008, "S4"},
        {ReferenceArea.EU27OutsideEuroArea16ExcludingDKSEGB2009, "S5"},
        {ReferenceArea.EU27OutsideEuroArea17ExcludingDKSEGB2011, "S6"},
        {ReferenceArea.EU28OutsideEuroArea17ExcludingDKSEGB2013, "S7"},
        {ReferenceArea.SaudiArabia, "SA"},
        {ReferenceArea.SolomonIslands, "SB"},
        {ReferenceArea.Seychelles, "SC"},
        {ReferenceArea.Sudan, "SD"},
        {ReferenceArea.Sweden, "SE"},
        {ReferenceArea.Singapore, "SG"},
        {ReferenceArea.SaintHelena, "SH"},
        {ReferenceArea.Slovenia, "SI"},
        {ReferenceArea.SvalbardAndJanMayen, "SJ"},
        {ReferenceArea.Slovakia, "SK"},
        {ReferenceArea.SierraLeone, "SL"},
        {ReferenceArea.SanMarino, "SM"},
        {ReferenceArea.Senegal, "SN"},
        {ReferenceArea.Somalia, "SO"},
        {ReferenceArea.Suriname, "SR"},
        {ReferenceArea.SouthSudan, "SS"},
        {ReferenceArea.SaoTomeAndPrincipe, "ST"},
        {ReferenceArea.ElSalvador, "SV"},
        {ReferenceArea.SintMaartenDutchPart, "SX"},
        {ReferenceArea.SyrianArabRepublic, "SY"},
        {ReferenceArea.Swaziland, "SZ"},
        {ReferenceArea.EuroArea11ExcludingLU1999, "T1"},
        {ReferenceArea.EuroAreaCountriesExceptGermanyFranceItalySpain, "T2"},
        {ReferenceArea.EuroAreaCountriesMovingExcludingDEFR, "T3"},
        {ReferenceArea.TurksAndCaicosIslands, "TC"},
        {ReferenceArea.Chad, "TD"},
        {ReferenceArea.FrenchSouthernTerritories, "TF"},
        {ReferenceArea.Togo, "TG"},
        {ReferenceArea.Thailand, "TH"},
        {ReferenceArea.Tajikistan, "TJ"},
        {ReferenceArea.Tokelau, "TK"},
        {ReferenceArea.TimorLeste, "TL"},
        {ReferenceArea.Turkmenistan, "TM"},
        {ReferenceArea.Tunisia, "TN"},
        {ReferenceArea.Tonga, "TO"},
        {ReferenceArea.Turkey, "TR"},
        {ReferenceArea.TrinidadAndTobago, "TT"},
        {ReferenceArea.Tuvalu, "TV"},
        {ReferenceArea.Taiwan, "TW"},
        {ReferenceArea.Tanzania, "TZ"},
        {ReferenceArea.EUExcludingEuroAreaAndReferenceArea, "U0"},
        {ReferenceArea.EuroAreaChangingComposition, "U2"},
        {ReferenceArea.EUMemberStatesNotBelongingToEuroArea, "U3"},
        {ReferenceArea.ExtraEuroArea, "U4"},
        {ReferenceArea.OtherEuroAreaMemberStates, "U5"},
        {ReferenceArea.Domestic, "U6"},
        {ReferenceArea.EuroAreaAndReferenceArea, "U7"},
        {ReferenceArea.AllAreasOtherThanEuroAreaAndReferenceArea, "U8"},
        {ReferenceArea.AllAreasOtherThanEUAndReferenceArea, "U9"},
        {ReferenceArea.Ukraine, "UA"},
        {ReferenceArea.Uganda, "UG"},
        {ReferenceArea.UnitedStatesMinorOutlyingIslands, "UM"},
        {ReferenceArea.UnitedStates, "US"},
        {ReferenceArea.Uruguay, "UY"},
        {ReferenceArea.Uzbekistan, "UZ"},
        {ReferenceArea.EU27FixedComposition2007, "V1"},
        {ReferenceArea.ExtraEU27FixedComposition2007, "V2"},
        {ReferenceArea.EU28FixedComposition2013, "V3"},
        {ReferenceArea.ExtraEU28FixedComposition2013, "V4"},
        {ReferenceArea.EU27FixedComposition2020, "V5"},
        {ReferenceArea.ExtraEU27FixedComposition2020, "V6"},
        {ReferenceArea.HolySee, "VA"},
        {ReferenceArea.SaintVincentAndTheGrenadines, "VC"},
        {ReferenceArea.Venezuela, "VE"},
        {ReferenceArea.VirginIslandsBritish, "VG"},
        {ReferenceArea.VirginIslandsUS, "VI"},
        {ReferenceArea.VietNam, "VN"},
        {ReferenceArea.Vanuatu, "VU"},
        {ReferenceArea.IntraEUChangingCompositionNotAllocated, "W0"},
        {ReferenceArea.GazaAndJericho, "W1"},
        {ReferenceArea.IntraEuroAreaNotAllocated, "W2"},
        {ReferenceArea.ExtraEuroAreaNotAllocated, "W4"},
        {ReferenceArea.ExtraEU25NotAllocated2004, "W5"},
        {ReferenceArea.ResidualForBOPAndIIPStep3ECBNeeds, "W6"},
        {ReferenceArea.IntraEU25NotAllocated2004, "W7"},
        {ReferenceArea.IntraEU27NotAllocated2007, "W8"},
        {ReferenceArea.ExtraEU27NotAllocated2007, "W9"},
        {ReferenceArea.WallisAndFutuna, "WF"},
        {ReferenceArea.Samoa, "WS"},
        {ReferenceArea.NotApplicable, "X0"},
        {ReferenceArea.Kosovo, "XK"},
        {ReferenceArea.Yemen, "YE"},
        {ReferenceArea.Mayotte, "YT"},
        {ReferenceArea.Yugoslavia, "YU"},
        {ReferenceArea.WorldNotAllocatedEU12, "Z0"},
        {ReferenceArea.WorldNotAllocatedEU15, "Z1"},
        {ReferenceArea.SmallEuroAreaCountries, "Z15"},
        {ReferenceArea.IntraEU12NotAllocated1993, "Z2"},
        {ReferenceArea.WorldNotAllocatedEuroArea, "Z3"},
        {ReferenceArea.ExtraEU12NotAllocated1993, "Z4"},
        {ReferenceArea.WorldNotAllocatedGeographically, "Z5"},
        {ReferenceArea.IntraEU15NotAllocated1995, "Z6"},
        {ReferenceArea.EquallySharedControlOfUCIs, "Z7"},
        {ReferenceArea.ExtraEU15NotAllocated1995, "Z8"},
        {ReferenceArea.RestOfTheWorld, "Z9"},
        {ReferenceArea.SouthAfrica, "ZA"},
        {ReferenceArea.Zambia, "ZM"},
        {ReferenceArea.Zimbabwe, "ZW"},
    }.ToImmutableDictionary();
}
